### ISSUE TITLE
Won't retrieve stockpiles

### ISSUE THREAD

**Issue by yland4** [tehruttiger/Stockpiler#10]
Not sure what i'm doing wrong, but anytime i try to retrieve a stock pile all i get back is outpost.(no outposts are even in the screen area). This happens on any stockpile i try to retriev
![ss+(2021-12-12+at+12 29 54)](https://user-images.githubusercontent.com/55366683/145702872-f8f3788d-f9ea-4fa4-946a-041bde7ec7d9.jpg)
![ss+(2021-12-12+at+12 31 08) (2)](https://user-images.githubusercontent.com/55366683/145702915-5b419c9e-19d9-4c3a-b66c-3fa2a2d73fc6.jpg)
e

**Comment by yland4** [comment]
Figured it out. It don't like the colored icons. All is well after removing that mod.

**Comment by tehruttiger** [comment]
The newest version just uploaded has a new mode that allows you to "teach" the program to use your mod.  When you scan with Learning Mode on, it will go one by one and ask you to identify every new icon it finds.  Please open a new issue if it doesn't work as expected.

Thanks!
