### ISSUE TITLE
Issues running program

### ISSUE THREAD

**Issue by RathfulConcepts** [tehruttiger/Stockpiler#13]
When I tried to follow the guide to using this, it kept returning "Stockpile wasnt found" while hovering over Callum's Cape seaport. After trying a couple more times, I check back to the app and all the item icons had disappeared

**Comment by tehruttiger** [comment]
Do you use multiple monitors?  If so, which monitor do you play Foxhole on (left/right)?

For disappearing icons, do you have it on Default or Modded icons?  Is learning mode on?

**Comment by RathfulConcepts** [comment]
I have 2 monitors, I play foxhole on my right one and use my left of discord/browser. I also use modded icons and have learning mode on, but due to never getting a stockpile open, i never got the option to use the icons

**Comment by tehruttiger** [comment]
So far, Stockpiler only works on the left monitor.  Grabbing screenshots for OpenCV is difficult on multi monitor setups.  As a test, could you move Foxhole to your left monitor and see if it works as expected?

**Comment by tehruttiger** [comment]
Multi-monitor working.  Bug should be resolved, but please reach out if not.
