### ISSUE TITLE
Modded icons setting breaks filters

### ISSUE THREAD

**Issue by vilobion** [tehruttiger/Stockpiler#16]
Steps to reproduce:
Start stockpiler
Select modded icons
Select a filter (At this point I see the message "create_window height for filter canvas should be roughly: -93")

Setting modded icons back to default and selecting a faction filter does reset the view.

**Comment by tehruttiger** [comment]
When you set this, do you have any new icons created yet?  If you have not yet "learned" some icons, the filter window has no items to build the window yet.  Once one or more items have had their icons learned, the filter window should begin to draw correctly with only the learned icons that you have so far.

**Comment by vilobion** [comment]
This is right out of the box with no icons learned- due to the other bug I've submitted I've never seen the window/popup for teaching/learning custom icons.

**Comment by tehruttiger** [comment]
> This is right out of the box with no icons learned- due to the other bug I've submitted I've never seen the window/popup for teaching/learning custom icons.

Learning mode is now working correctly.  I need to compile a fresh version after all the changes I've pushed.  After that, I'll see if I can replicate the issue you describe.

**Comment by tehruttiger** [comment]
No longer an issue so far as I can tell.  Will reopen if that's not the case.
