### ISSUE TITLE
Didn't detect stockpile. Error

### ISSUE THREAD

**Issue by PeteNotFound** [tehruttiger/Stockpiler#21]
When I try scanning a stockpile I get the following message box:
![image](https://user-images.githubusercontent.com/20028431/167393650-8fa106ab-a84b-4b94-82f2-794ab92d934e.png)
The Stockpiler went through the modded learning without any problems and F2 takes a screenshot of the stockpile without any problems(Stockpile contents have been censored for obvious reasons):
![test_2022-05-09-122737](https://user-images.githubusercontent.com/20028431/167393891-e2172e84-c3bc-4aa2-a657-e220c758edb0.png)
Tried with and without mods, with different Stockpiler settings and on different stockpiles(Bunker Base, Seaport(Public and reserved stockpile), Town Base).

**Comment by tehruttiger** [comment]
Interesting.  So it's still finding and cropping the stockpile, but just not successfully reading and tallying the results.  Did it ask you to transcribe the title of the stockpile?

**Comment by tehruttiger** [comment]
What specific error/message are you getting in the console window?

**Comment by PeteNotFound** [comment]
My console looks exactly the same.

**Comment by tehruttiger** [comment]
Yeah, I'm going to pull all that out of a try loop so I can get a specific error.  It's not giving us anything to go on there.

**Comment by tehruttiger** [comment]
Issue was a lowercase k in cv2.waitkey(0) which should have been cv2.waitKey(0).  Gotta love it.  Commented out and tested working.
