### ISSUE TITLE
Update for upcoming 1.0 Inferno

### ISSUE THREAD

**Issue by BGASM** [tehruttiger/Stockpiler#30]
Hello,

Awesome script. I was trying to build this exact piece of software but I stumbled upon your project.

I wanted to ask if you are currently developing for the upcoming Inferno update and new facility materials.

**Comment by tehruttiger** [comment]
Finally had a chance to add the new items.  Submitting a new release shortly.  I don't have all the icons yet, but you can use Learning Mode to collect them yourself.  Just make sure to message me in Discord and send any missing icons my way so I can get them added.
