### ISSUE TITLE
include /.venv in .gitignore file

### ISSUE THREAD

**Issue by AlpBilgin** [tehruttiger/Stockpiler#35]
Hello it's me again,

you may want to encourage people who don't use conda to use a common venv folder name and add that to the .gitignore file. 

I personally prefer .venv but anthing is ok really.

in case you don't know what this is about => https://docs.python.org/3/library/venv.html

**Comment by Maelstromeous** [comment]
👍 venv is great for onboarding as it just creates all the deps for just that app only

**Comment by Tkaixiang** [comment]
This has been added in 5c872d1507e2ac69efa2303283771b411c314d71
