### ISSUE TITLE
Expanded Stockpile Screenshot

### ISSUE THREAD

**Issue by Glaneib** [tehruttiger/Stockpiler#43]
First of all, just want to say that I'm very happy to have found this app/tool and cant wait to really give it a go in the next war that my regi is joining in. If anything, I'm a bit sad it took me as long as it did to stumble upon!

So the issue I've encountered is actually highly likely due to the new update the Devs are rolling out, but simply put it seems like the app takes a screenshot only 'x' pixels wide, but this is cutting off the rest of the stockpile because the Devs extended the width (I also think this is causing the app to not read stockpile names, as I've yet to see a prompt for a name, but could be user error)

Currently what the app shows/old stockpile size:
![Seaport image](https://user-images.githubusercontent.com/120355654/206964705-3cbd849e-01d3-4bf1-a4c0-0b05ed4cc996.png)

New stockpile size:
![image](https://user-images.githubusercontent.com/120355654/206964788-b4e2ee8c-239a-4c43-b257-f48ff9242d58.png)

As far as I could tell with my limited testing (so far) it seems like the app _is_ reading all the items in the stockpile, it just isn't printing out a full picture of the stockpile either in the image file or the report (see below, it's missing the last two lines from my "new" screenshot)
![image](https://user-images.githubusercontent.com/120355654/206965405-5c385a93-71b4-45f1-bcea-517131f38baa.png)

I hope I've explained the issue well enough for you, I'd love to start using this day 1 of the new war, but I know how things can be!

Quick Edit: I havent played the main shards since they shutdown our shard (RIP Baker), so this has all been on the Dev branch, no clue if A/C have the expanded stockpiles yet or not or if it's really the Dev branch causing issues.

**Comment by Romboter** [comment]
Fixed in PR #45

**Comment by Tkaixiang** [comment]
Fixed in #45
