### ISSUE TITLE
Missing update 51 and 52 items.

### ISSUE THREAD

**Issue by CritteRo** [tehruttiger/Stockpiler#47]
Currently, Stockpiler does not recognize the following items:
- Fissura (tripod grenade launcher)
- Havoc Charge
- Havoc Charge Detonator

Also, Garrison Supplies needs to be renamed to Maintenance Supplies.

**Comment by instantae** [comment]
other missing items: 

- Lordscar
- Knave
- Flood MkI 
- Hasta
- Lance-36
- Flood Juggernaut
- Cullen Predator
- Ares
- Dousing Engine 3r
- R-12b Salva
