### ISSUE TITLE
Missing stuff in filters.csv and checkimages/default

### ISSUE THREAD

**Issue by instantae** [tehruttiger/Stockpiler#52]
filter.csv only goes to item ID 281 so Hawthorne and ACV arent recognized

**Comment by instantae** [comment]
fix + update 54 additions (without naval components): [https://github.com/instantae/Stockpiler/releases/tag/v1.54](here)

**Comment by Tkaixiang** [comment]
Heyo, sorry for the late reply but someone else has helped compile all the new items and a new version has been posted
