### ISSUE TITLE
Learning mode doesn't seem to work

### ISSUE THREAD

**Issue by al-arz** [tehruttiger/Stockpiler#54]
Looks like Learning mode doesn't work without "Compare" folder, which is missing in precompiled build.

Related: https://github.com/tehruttiger/Stockpiler/issues/49

https://github.com/tehruttiger/Stockpiler/commit/07ddad2c5b8c81a843c02c9c711252e223d4d30d might be the culprit? @Tkaixiang

**Comment by Tkaixiang** [comment]
Yup it is, fixed in b2ebb99cced0e533e16119d6bbd53a60dd667c71
